# Travis-CI Build for sltbench
# see travis-ci.org for details

dist: xenial

language: cpp

matrix:
  include:

    - os: linux
      compiler: clang       

    - os: linux
      compiler: gcc

    - os: osx

script:
  - mkdir build 
  - cd build
  - cmake -DSLT_BUILD_TESTS=ON -DSLT_BUILD_EXAMPLES=ON -DSLT_BUILD_HISTOGRAMMER=ON -DSLT_BUILD_AUTOLEARNING=ON ..
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then cmake --build . --parallel; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then make -j$(sysctl -n hw.ncpu); fi
  - ./tests/sltbench_unittests
